// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHKXUA0ak5rKYKK2sCR4C7YLnIo1IXl5c',
    appId: '1:1006926029707:web:c2ac5f97735f7a0eac058e',
    messagingSenderId: '1006926029707',
    projectId: 'mobidati',
    authDomain: 'mobidati.firebaseapp.com',
    storageBucket: 'mobidati.appspot.com',
    measurementId: 'G-22GQM0RR3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq_QMngWeJsXTVd05kpk1GbJu0283GlyM',
    appId: '1:1006926029707:android:f1136074739373b4ac058e',
    messagingSenderId: '1006926029707',
    projectId: 'mobidati',
    storageBucket: 'mobidati.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zccJX3voAsSQ3CsG6QiTQHYsfWqPl2g',
    appId: '1:1006926029707:ios:253685e08eb01b84ac058e',
    messagingSenderId: '1006926029707',
    projectId: 'mobidati',
    storageBucket: 'mobidati.appspot.com',
    iosBundleId: 'com.example.dashBoardMopidati',
  );
}
